version: '3.4'

networks:
 backend:

services:
  customerdb:
    container_name: customer-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@123
    networks:
      - backend
    ports:
     - 8001:1433
  customerwebapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: CustomerWebApi/Dockerfile
    networks:
      - backend 
    ports:
      - 8002:80
    environment:
     - DB_HOST=customerdb
     - DB_SA_PASSWORD=Pass@123
     - DB_NAME=customer
  productdb:
    container_name: product-db
    image: mysql:8.0.29-oracle
    ports:
     - 8003:3306
    environment:
     - MYSQL_ROOT_PASSWORD=""
    networks:
     - backend
  productwebapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productwebapi
    build:
      context: .
      dockerfile: ProductWebApi/Dockerfile
    networks:
      - backend
    ports:
     - 8004:80
    environment:
      - DB_HOST=productdb
      - DB_ROOT_PASSWORD=""
      - DB_NAME=product
